basic_settings:
  site_title: Haus zur Miete
  site_tagline: Einfamilienhaus in Bergneustadt zu vermieten
  favicon_image: /images/favicon.ico
  description: Sehr schönes Einfamilienhaus in Bergneustadt zu vermieten.


advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""